# Generated by Django 4.1 on 2024-07-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_actor_cinemahall_genre_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemahall',
            options={},
        ),
    ]
